---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# CovidPlot19

<!-- badges: start -->
<!-- badges: end -->

This repo is an R package implemented to get covid19 data from Jhon Hopkins university’s CSSEGISandData repository and draw some plots about the covid-19 pandemic.

## Installation

You can install the development version from [GitHub](https://github.com/alibalapour/CovidPlot19) with:


``` {r}
# install.packages("devtools")
# devtools::install_github("alibalapour/CovidPlot19")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
# library(CovidPlot19)
# df <- suppressWarnings(suppressMessages(getData()))
# head(df, 20)
```


```{r plotWorldMap}
# plotOnWorldMap(date = '2020-05-03', type = 'Cases')
```



```{r plotTimeSeries, echo = FALSE}
# plotTimeSeries(startDate = '2020-03-10',
#                endDate = '2020-10-10',
#                country = 'US',
#                type = 'DailyCases'
#                )
```
